parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            string $uploadPath: "%kernel.project_dir%/public/uploads/images"

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
